### PR TITLE
index with ES6

### PR DESCRIPTION
**Pull request by behnammodi**

### CODE REVIEW

**Comment by behrang** [comment]
Thanks. I really prefer the old style for this project, since it is a base implementation of the algorithm and new implementations will be based on this.

**Comment by behnammodi** [comment]
i don't change your algorithm just change style to ES6

**Comment by behrang** [comment]
I know. I mean keeping `function`s on the top level will help new comers from other languages to convert it.

**Comment by behnammodi** [comment]
this isn't alternative for index.js file

**Comment by behnammodi** [comment]
we can create new repository with this name "jalaali-js-es6"

**Comment by behrang** [comment]
What is the value?

**Comment by behnammodi** [comment]
maybe help for learning or developers like to use ES6 style or "jalaali" repository will complete with all language.

this is just proposal

thank you.

**Comment by behrang** [comment]
Sorry for rejecting, but this would add more confusion.

**Comment by behnammodi** [comment]
good job

**Pull request closed without merging**
