### PR TITLE
Clean code and update dev dependencies

### PR DESCRIPTION
**Pull request by behnammodi**
All test is ok

### CODE REVIEW

**Comment by behrang** [comment]
I don't get the reason for this change. You have also removed a field from the return value. Also another `if` statement is added. Why?

**Comment by behnammodi** [comment]
@behrang Thank you for review code
1- No added new `if` and just replaced
2- This field unused when `withoutLeap` is `true`
3- I used multi exit points for readability

**Comment by behrang** [comment]
Ok, merged. Thanks.

**Comment by behnammodi** [comment]
You’re welcome

**Pull request merged**
