### PR TITLE
Add time params to jalaaliToDateObject method

### PR DESCRIPTION
**Pull request by mhsattarian**

### CODE REVIEW

**Comment by behrang** [comment]
Hey,

Thanks for the PR. However, I see that you've used default parameters, which is a ES2015 feature. Even though most browsers support it, I believe this library is written in the old style (for example uses `var` instead of `const` and `let`). So It's better to keep it that way. 

I think maybe just dropping the `= null` part from the function definition will be enough.

It would be great if you add a few test cases too.

**Comment by mhsattarian** [comment]
You're right. I fixed the default params in a new commit.

will add the test too in the next one.

**Comment by mhsattarian** [comment]
I've added tests for `jalaaliToDateObject` with _time params_, and run them locally. everything looks fine.

here's a screenshot, just in case:

image

**Comment by behrang** [comment]
Thanks, merged.

**Pull request merged**
